/**
 * YoloBox Companion Module - Constants
 * Reused from the StreamDeck plugin, converted to ESM exports
 */

export const ActionTypes = {
	BOOLEAN: 1,
	FLOAT: 2,
	MODE: 4,
	COMMAND: 5,
	RANGE: 6,
	ANY: 7,
	DYNAMIC: 8,
	CYCLE: 9,
}

export const DEFAULT_PORT = 8889
export const HEARTBEAT_INTERVAL = 10000
export const RECONNECT_INTERVAL = 5000
export const CONNECTION_TIMEOUT = 5000

export const WebSocketEndpoints = {
	SUBSCRIBER: 'subscriber',
	HEARTBEAT: 'heartbeat',
	TEST: 'test',
	SPECIFICATION: 'specification',
}

/**
 * Action registry — each key is the actionId used in Companion
 */
export const ActionRegistry = {
	// 1. Video Source
	source: {
		group: 'VIDEO SOURCE',
		category: 'Video Source',
		hasState: false,
		defaultFunction: 'source1',
		stateIcons: {
			unselected: 'source_unselected',
			selected: 'source_selected',
			preview: 'source_preview',
			multiSelected: 'source_multi_selected',
		},
		functions: [
			{
				name: 'source1',
				description: 'Source 1',
				property: 'preview_source_1',
				value: 0,
				actionType: ActionTypes.DYNAMIC,
				icon: 'source_1',
				defaultDescription: 'Source 1',
			},
			{
				name: 'source2',
				description: 'Source 2',
				property: 'preview_source_2',
				value: 0,
				actionType: ActionTypes.DYNAMIC,
				icon: 'source_2',
				defaultDescription: 'Source 2',
			},
			{
				name: 'source3',
				description: 'Source 3',
				property: 'preview_source_3',
				value: 0,
				actionType: ActionTypes.DYNAMIC,
				icon: 'source_3',
				defaultDescription: 'Source 3',
			},
			{
				name: 'source4',
				description: 'Source 4',
				property: 'preview_source_4',
				value: 0,
				actionType: ActionTypes.DYNAMIC,
				icon: 'source_4',
				defaultDescription: 'Source 4',
			},
			{
				name: 'source5',
				description: 'Source 5',
				property: 'preview_source_5',
				value: 0,
				actionType: ActionTypes.DYNAMIC,
				icon: 'source_5',
				defaultDescription: 'Source 5',
			},
			{
				name: 'source6',
				description: 'Source 6',
				property: 'preview_source_6',
				value: 0,
				actionType: ActionTypes.DYNAMIC,
				icon: 'source_6',
				defaultDescription: 'Source 6',
			},
			{
				name: 'source7',
				description: 'Source 7',
				property: 'preview_source_7',
				value: 0,
				actionType: ActionTypes.DYNAMIC,
				icon: 'source_7',
				defaultDescription: 'Source 7',
			},
			{
				name: 'source8',
				description: 'Source 8',
				property: 'preview_source_8',
				value: 0,
				actionType: ActionTypes.DYNAMIC,
				icon: 'source_8',
				defaultDescription: 'Source 8',
			},
			{
				name: 'source9',
				description: 'Source 9',
				property: 'preview_source_9',
				value: 0,
				actionType: ActionTypes.DYNAMIC,
				icon: 'source_9',
				defaultDescription: 'Source 9',
			},
			{
				name: 'source10',
				description: 'Source 10',
				property: 'preview_source_10',
				value: 0,
				actionType: ActionTypes.DYNAMIC,
				icon: 'source_10',
				defaultDescription: 'Source 10',
			},
		],
	},

	// 2. Overlay
	overlay: {
		group: 'Overlay',
		category: 'Overlay',
		hasState: true,
		defaultFunction: 'overlay1',
		stateIcons: {
			unselected: 'overlay_unselected',
			program: 'overlay_program',
		},
		functions: [
			{
				name: 'overlay1',
				description: 'Overlay 1',
				property: 'Overlay_1',
				value: 0,
				actionType: ActionTypes.DYNAMIC,
				icon: 'overlay_source1_unselect',
			},
			{
				name: 'overlay2',
				description: 'Overlay 2',
				property: 'Overlay_2',
				value: 0,
				actionType: ActionTypes.DYNAMIC,
				icon: 'overlay_source2_unselect',
			},
			{
				name: 'overlay3',
				description: 'Overlay 3',
				property: 'Overlay_3',
				value: 0,
				actionType: ActionTypes.DYNAMIC,
				icon: 'overlay_source3_unselect',
			},
			{
				name: 'overlay4',
				description: 'Overlay 4',
				property: 'Overlay_4',
				value: 0,
				actionType: ActionTypes.DYNAMIC,
				icon: 'overlay_source4_unselect',
			},
			{
				name: 'overlay5',
				description: 'Overlay 5',
				property: 'Overlay_5',
				value: 0,
				actionType: ActionTypes.DYNAMIC,
				icon: 'overlay_source5_unselect',
			},
			{
				name: 'overlay6',
				description: 'Overlay 6',
				property: 'Overlay_6',
				value: 0,
				actionType: ActionTypes.DYNAMIC,
				icon: 'overlay_source6_unselect',
			},
			{
				name: 'overlay7',
				description: 'Overlay 7',
				property: 'Overlay_7',
				value: 0,
				actionType: ActionTypes.DYNAMIC,
				icon: 'overlay_source7_unselect',
			},
			{
				name: 'overlay8',
				description: 'Overlay 8',
				property: 'Overlay_8',
				value: 0,
				actionType: ActionTypes.DYNAMIC,
				icon: 'overlay_source8_unselect',
			},
			{
				name: 'overlay9',
				description: 'Overlay 9',
				property: 'Overlay_9',
				value: 0,
				actionType: ActionTypes.DYNAMIC,
				icon: 'overlay_source9_unselect',
			},
			{
				name: 'overlay10',
				description: 'Overlay 10',
				property: 'Overlay_10',
				value: 0,
				actionType: ActionTypes.DYNAMIC,
				icon: 'overlay_source10_unselect',
			},
		],
	},

	// 3. Stream & Record
	stream_record: {
		group: 'Stream&Record',
		category: 'Stream & Record',
		hasState: true,
		defaultFunction: 'goLive',
		functions: [
			{
				name: 'goLive',
				description: 'Go Live/Pause Live',
				group: 'Live Streaming',
				property: 'live_state',
				value: 0,
				actionType: ActionTypes.BOOLEAN,
				icon: 'live_go',
				iconOn: 'live_end',
			},
			{
				name: 'record',
				description: 'Record/Stop Recording',
				group: 'Recording',
				property: 'record_state',
				value: 0,
				actionType: ActionTypes.BOOLEAN,
				icon: 'keyboard_start_record',
				iconOn: 'keyboard_end_record',
			},
			{
				name: 'programMax',
				description: 'Program Max',
				group: 'LiveStream',
				property: 'preview_mode',
				value: 1,
				actionType: ActionTypes.COMMAND,
				icon: 'program_max',
				iconOn: 'program_max',
			},
			{
				name: 'pgmOut',
				description: 'HDMI OUT1 Mode',
				group: 'Preview',
				property: 'pgm_toggle',
				actionType: ActionTypes.CYCLE,
				cycleValues: [0, 1, 2, 3],
				icons: ['hdmi1_out_program', 'hdmi1_out_multiview', 'hdmi1_out_custom', 'hdmi1_out_mirror'],
			},
			{
				name: 'pgmOut2',
				description: 'HDMI OUT2 Mode',
				group: 'Preview',
				property: 'pgm_toggle_two',
				actionType: ActionTypes.CYCLE,
				cycleValues: [0, 1, 2, 3],
				icons: ['hdmi2_out_program', 'hdmi2_out_multiview', 'hdmi2_out_custom', 'hdmi2_out_mirror'],
			},
		],
	},

	// 4. Director Mode
	director_mode: {
		group: 'Preview',
		category: 'Director Mode',
		hasState: true,
		defaultFunction: 'previewToProgram',
		functions: [
			{
				name: 'previewToProgram',
				description: 'Preview To Program',
				property: 'preview_to_program',
				value: 0,
				actionType: ActionTypes.BOOLEAN,
				toggle: false,
				icon: 'pvwtopgm_enable',
				iconOn: 'pvwtopgm_unenable',
			},
			{
				name: 'directorTransitionMethod',
				description: 'Director Transition Method',
				property: 'transition_ptp_type',
				actionType: ActionTypes.CYCLE,
				cycleValues: [0, 1, 2],
				icons: ['mode_cut_enable', 'mode_fade_enable', 'mode_wipe_enable'],
			},
			{
				name: 'switchMethod',
				description: 'Switch Method',
				property: 'transition_ptp_dir',
				actionType: ActionTypes.CYCLE,
				cycleValues: [0, 1],
				icons: ['mode_ptp_enable', 'mode_single_enable'],
			},
		],
	},

	// 5. Transitions
	transition: {
		group: 'Transitions',
		category: 'Transitions',
		hasState: true,
		defaultFunction: 'ftb',
		functions: [
			{
				name: 'ftb',
				description: 'FTB',
				group: 'Preview',
				property: 'fbk_toggle',
				value: 0,
				actionType: ActionTypes.BOOLEAN,
				icon: 'ftb_open',
				iconOn: 'ftb_close',
			},
			{
				name: 'transitionDuration',
				description: 'Transition Duration',
				group: 'Transitions',
				property: 'transitions_duration',
				actionType: ActionTypes.CYCLE,
				cycleValues: [0, 1, 2, 3, 4, 5],
				icons: ['trans_time_0', 'trans_time_1', 'trans_time_2', 'trans_time_3', 'trans_time_4', 'trans_time_5'],
			},
			{
				name: 'transitionMethod',
				description: 'Transition method',
				group: 'Transitions',
				property: 'transitions_type',
				actionType: ActionTypes.CYCLE,
				cycleValues: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
				icons: [
					'trans_cut',
					'trans_fade',
					'trans_wipe',
					'trans_directionalwipe',
					'trans_translation',
					'trans_windowslice',
					'trans_simplwzoom',
					'trans_crosszoom',
					'trans_squeeze',
					'trans_flippage',
					'trans_cube',
				],
			},
		],
	},

	// 6. Replay
	replay: {
		group: 'Replay',
		category: 'Replay',
		hasState: true,
		defaultFunction: 'replay',
		functions: [
			{
				name: 'replay',
				description: 'Start Replay',
				property: 'replay_state',
				value: 0,
				actionType: ActionTypes.BOOLEAN,
				icon: 'replay_start',
				iconOn: 'replay_stop',
			},
			{
				name: 'capture',
				description: 'Capture Replay',
				property: 'replay_capture',
				value: 0,
				actionType: ActionTypes.COMMAND,
				icon: 'replay_capture',
			},
			{
				name: 'playLast',
				description: 'Start Play Last',
				property: 'play_last',
				value: 1,
				actionType: ActionTypes.COMMAND,
				icon: 'play_last_replay',
			},
			{
				name: 'markIn',
				description: 'Mark In',
				property: 'mark_replay',
				value: 0,
				actionType: ActionTypes.BOOLEAN,
				icon: 'mark_in',
				iconOn: 'mark_out',
			},
		],
	},

	// 7. Auto Switch
	auto_switch: {
		group: 'AUTO FUNCTION',
		category: 'Auto Switch',
		hasState: true,
		defaultFunction: 'autoSwitch',
		functions: [
			{
				name: 'autoSwitch',
				description: 'Auto Switch',
				group: 'AUTO FUNCTION',
				property: 'AUTOSWITCH',
				value: 0,
				actionType: ActionTypes.BOOLEAN,
				icon: 'autoswitch_select',
				iconOn: 'autoswitch_unselect',
			},
			{
				name: 'vfa',
				description: 'VFA',
				group: 'AUTO FUNCTION',
				property: 'VFA',
				value: 0,
				actionType: ActionTypes.BOOLEAN,
				icon: 'vfa_select',
				iconOn: 'vfa_unselect',
			},
		],
	},

	// 8. Audio
	audio: {
		group: 'Audio',
		category: 'Audio',
		hasState: true,
		defaultFunction: 'audioFade',
		functions: [
			{
				name: 'audioFade',
				description: 'Audio Fade',
				group: 'Audio',
				property: 'audio_fade',
				value: 0,
				actionType: ActionTypes.BOOLEAN,
				icon: 'audio_fade_select',
				iconOn: 'audio_fade_unselect',
			},
			{
				name: 'programAudio',
				description: 'Program Audio',
				group: 'Audio',
				property: 'program_state',
				value: 0,
				actionType: ActionTypes.BOOLEAN,
				icon: 'audio_program_on',
				iconOn: 'audio_program_off',
			},
			{
				name: 'pgmVolumePlus',
				description: 'PGM Volume +',
				group: 'Audio',
				property: 'PGM_VOLUME_PLUS',
				value: 0,
				actionType: ActionTypes.COMMAND,
				icon: 'pgm_volume_plus',
			},
			{
				name: 'pgmVolumeMinus',
				description: 'PGM Volume -',
				group: 'Audio',
				property: 'PGM_VOLUME_REDUCE',
				value: 0,
				actionType: ActionTypes.COMMAND,
				icon: 'pgm_volume_reduce',
			},
			{
				name: 'monitorVolumePlus',
				description: 'Monitor Volume +',
				group: 'Audio',
				property: 'MONITOR_VOLUME_PLUS',
				value: 0,
				actionType: ActionTypes.COMMAND,
				icon: 'monitor_volume_plus',
			},
			{
				name: 'monitorVolumeMinus',
				description: 'Monitor Volume -',
				group: 'Audio',
				property: 'MONITOR_VOLUME_REDUCE',
				value: 0,
				actionType: ActionTypes.COMMAND,
				icon: 'monitor_volume_reduce',
			},
		],
	},

	// 9. BGM Music
	bgm: {
		group: 'Background Music',
		category: 'BGM Music',
		hasState: true,
		defaultFunction: 'playPause',
		functions: [
			{
				name: 'playMode',
				description: 'Play Mode',
				group: 'Background Music',
				property: 'play_mode',
				actionType: ActionTypes.CYCLE,
				cycleValues: [0, 1, 2, 3],
				icons: ['bgm_mode_1', 'bgm_mode_2', 'bgm_mode_3', 'bgm_mode_4'],
			},
			{
				name: 'playPause',
				description: 'Play/Pause',
				group: 'Background Music',
				property: 'play_status',
				value: 0,
				actionType: ActionTypes.BOOLEAN,
				icon: 'bgm_start',
				iconOn: 'bgm_pause',
			},
			{
				name: 'nextBgm',
				description: 'Next BGM',
				group: 'Background Music',
				property: 'next_song',
				value: 0,
				actionType: ActionTypes.COMMAND,
				icon: 'bgm_next',
			},
			{
				name: 'prevBgm',
				description: 'Previous BGM',
				group: 'Background Music',
				property: 'prev_song',
				value: 0,
				actionType: ActionTypes.COMMAND,
				icon: 'bgm_prev',
			},
			{
				name: 'volumePlus',
				description: 'BGM Volume +',
				group: 'Background Music',
				property: 'bgm_plus',
				value: 0,
				actionType: ActionTypes.COMMAND,
				icon: 'bgm_volume_plus',
			},
			{
				name: 'volumeMinus',
				description: 'BGM Volume -',
				group: 'Background Music',
				property: 'bgm_minus',
				value: 0,
				actionType: ActionTypes.COMMAND,
				icon: 'bgm_volume_reduce',
			},
		],
	},

	// 10. Local Video
	local_video: {
		group: 'Local Video',
		category: 'Play/Pause Local Video',
		property: 'local_video',
		actionType: ActionTypes.BOOLEAN,
		hasState: true,
		icon: 'local_video_play',
		iconOn: 'local_video_pause',
	},

	// 11. PDF
	page_control: {
		group: 'LiveStream',
		category: 'PDF Page',
		hasState: false,
		defaultFunction: 'nextPage',
		functions: [
			{
				name: 'nextPage',
				description: 'Next Page',
				property: 'pdf_mode',
				actionType: ActionTypes.COMMAND,
				value: 1,
				icon: 'page_next',
			},
			{
				name: 'lastPage',
				description: 'Last Page',
				property: 'pdf_mode',
				actionType: ActionTypes.COMMAND,
				value: 0,
				icon: 'page_last',
			},
		],
	},

	// 12. Image
	image: {
		group: 'LiveStream',
		category: 'Image',
		hasState: false,
		defaultFunction: 'nextPage',
		functions: [
			{
				name: 'nextPage',
				description: 'Image Next Page',
				property: 'images_next',
				value: 0,
				actionType: ActionTypes.COMMAND,
				icon: 'image_next_page',
			},
			{
				name: 'lastPage',
				description: 'Image Last Page',
				property: 'images_last',
				value: 0,
				actionType: ActionTypes.COMMAND,
				icon: 'image_last_page',
			},
		],
	},

	// 13. Scoreboard
	scoreboard: {
		group: 'SCOREBOARD',
		category: 'Scoreboard',
		hasState: true,
		defaultFunction: 'scoreboard',
		functions: [
			{
				name: 'scoreboard',
				description: 'Scoreboard',
				group: 'SCOREBOARD',
				property: 'scoreboard_state',
				value: 0,
				actionType: ActionTypes.BOOLEAN,
				icon: 'scoreboard_on',
				iconOn: 'scoreboard_off',
			},
			{
				name: 'scoreboardTime',
				description: 'Scoreboard Time',
				group: 'SCOREBOARD',
				property: 'scoretime_state',
				value: 0,
				actionType: ActionTypes.BOOLEAN,
				icon: 'score_time_select',
				iconOn: 'score_time_unselect',
			},
			{
				name: 'timeStartPause',
				description: 'Time Start/Pause',
				group: 'SCOREBOARD',
				property: 'time_state',
				value: 0,
				actionType: ActionTypes.BOOLEAN,
				icon: 'score_start_time',
				iconOn: 'score_pause_time',
			},
			{
				name: 'homePlus1',
				description: 'Home Score +1',
				group: 'SCOREBOARD',
				property: 'home_Score_Plus1',
				value: 3,
				actionType: ActionTypes.MODE,
				icon: 'home_score_plus1',
			},
			{
				name: 'homePlus2',
				description: 'Home Score +2',
				group: 'SCOREBOARD',
				property: 'home_Score_Plus2',
				value: 4,
				actionType: ActionTypes.MODE,
				icon: 'home_score_plus2',
			},
			{
				name: 'homePlus3',
				description: 'Home Score +3',
				group: 'SCOREBOARD',
				property: 'home_Score_Plus3',
				value: 5,
				actionType: ActionTypes.MODE,
				icon: 'home_score_plus3',
			},
			{
				name: 'homeMinus1',
				description: 'Home Score -1',
				group: 'SCOREBOARD',
				property: 'home_Score_Minus1',
				value: 0,
				actionType: ActionTypes.MODE,
				icon: 'home_score_minus1',
			},
			{
				name: 'homeMinus2',
				description: 'Home Score -2',
				group: 'SCOREBOARD',
				property: 'home_Score_Minus2',
				value: 1,
				actionType: ActionTypes.MODE,
				icon: 'home_score_minus2',
			},
			{
				name: 'homeMinus3',
				description: 'Home Score -3',
				group: 'SCOREBOARD',
				property: 'home_Score_Minus3',
				value: 2,
				actionType: ActionTypes.MODE,
				icon: 'home_score_minus3',
			},
			{
				name: 'awayPlus1',
				description: 'Away Score +1',
				group: 'SCOREBOARD',
				property: 'away_Score_Plus1',
				value: 9,
				actionType: ActionTypes.MODE,
				icon: 'away_score_plus1',
			},
			{
				name: 'awayPlus2',
				description: 'Away Score +2',
				group: 'SCOREBOARD',
				property: 'away_Score_Plus2',
				value: 10,
				actionType: ActionTypes.MODE,
				icon: 'away_score_plus2',
			},
			{
				name: 'awayPlus3',
				description: 'Away Score +3',
				group: 'SCOREBOARD',
				property: 'away_Score_Plus3',
				value: 11,
				actionType: ActionTypes.MODE,
				icon: 'away_score_plus3',
			},
			{
				name: 'awayMinus1',
				description: 'Away Score -1',
				group: 'SCOREBOARD',
				property: 'away_Score_Minus1',
				value: 6,
				actionType: ActionTypes.MODE,
				icon: 'away_score_minus1',
			},
			{
				name: 'awayMinus2',
				description: 'Away Score -2',
				group: 'SCOREBOARD',
				property: 'away_Score_Minus2',
				value: 7,
				actionType: ActionTypes.MODE,
				icon: 'away_score_minus2',
			},
			{
				name: 'awayMinus3',
				description: 'Away Score -3',
				group: 'SCOREBOARD',
				property: 'away_Score_Minus3',
				value: 8,
				actionType: ActionTypes.MODE,
				icon: 'away_score_minus3',
			},
		],
	},

	// 14. Comment
	comment: {
		group: 'COMMENT',
		category: 'Comment',
		hasState: false,
		defaultFunction: 'feature',
		functions: [
			{
				name: 'feature',
				description: 'Feature The Comment',
				group: 'COMMENT',
				property: 'FEATURE_TO_COMMENT',
				value: 1,
				actionType: ActionTypes.COMMAND,
				icon: 'keyboard_feature_comment',
			},
			{
				name: 'hide',
				description: 'Hide The Comment',
				group: 'COMMENT',
				property: 'HIDE_THE_COMMENT',
				value: 0,
				actionType: ActionTypes.COMMAND,
				icon: 'keyboard_hide_comment',
			},
		],
	},

	// 15. Tab Switch
	tab_switch: {
		group: 'Menu',
		category: 'Tab Switch',
		hasState: false,
		defaultFunction: 'overlay',
		functions: [
			{
				name: 'overlay',
				description: 'Switch To Overlay Tab',
				property: 'menu_switch',
				value: 2,
				actionType: ActionTypes.COMMAND,
				icon: 'tab_switch_to_overlay',
			},
			{
				name: 'audioMixing',
				description: 'Switch To Audio Mixing Tab',
				property: 'menu_switch',
				value: 1,
				actionType: ActionTypes.COMMAND,
				icon: 'tab_switch_to_audio_console',
			},
			{
				name: 'bgm',
				description: 'Switch To BGM Tab',
				property: 'menu_switch',
				value: 4,
				actionType: ActionTypes.COMMAND,
				icon: 'tab_switch_to_bgm',
			},
			{
				name: 'comment',
				description: 'Switch To Comment Tab',
				property: 'menu_switch',
				value: 3,
				actionType: ActionTypes.COMMAND,
				icon: 'tab_switch_to_comment',
			},
			{
				name: 'scoreboard',
				description: 'Switch To Scoreboard Tab',
				property: 'menu_switch',
				value: 5,
				actionType: ActionTypes.COMMAND,
				icon: 'tab_switch_to_scoreboard',
			},
			{
				name: 'transitions',
				description: 'Switch To Transitions Tab',
				property: 'menu_switch',
				value: 6,
				actionType: ActionTypes.COMMAND,
				icon: 'tab_switch_to_trans',
			},
		],
	},

	// 16. PTZ
	ptz: {
		group: 'PTZ',
		category: 'PTZ Control',
		hasState: false,
		defaultFunction: 'position1',
		functions: [
			{
				name: 'position1',
				description: 'PTZ Position 1',
				property: 'ptz_set_position_1',
				value: 0,
				actionType: ActionTypes.MODE,
				icon: 'ic_ptz_position_1',
			},
			{
				name: 'position2',
				description: 'PTZ Position 2',
				property: 'ptz_set_position_2',
				value: 1,
				actionType: ActionTypes.MODE,
				icon: 'ic_ptz_position_2',
			},
			{
				name: 'position3',
				description: 'PTZ Position 3',
				property: 'ptz_set_position_3',
				value: 2,
				actionType: ActionTypes.MODE,
				icon: 'ic_ptz_position_3',
			},
			{
				name: 'position4',
				description: 'PTZ Position 4',
				property: 'ptz_set_position_4',
				value: 3,
				actionType: ActionTypes.MODE,
				icon: 'ic_ptz_position_4',
			},
			{
				name: 'position5',
				description: 'PTZ Position 5',
				property: 'ptz_set_position_5',
				value: 4,
				actionType: ActionTypes.MODE,
				icon: 'ic_ptz_position_5',
			},
		],
	},
}

/**
 * Reverse mapping from device property to Action
 * Used when receiving device state updates to locate the corresponding action and function
 */
export const PropertyToActionMap = {
	// Toggle type
	live_state: { actionId: 'stream_record', type: 'toggle', functionName: 'goLive' },
	record_state: { actionId: 'stream_record', type: 'toggle', functionName: 'record' },
	fbk_toggle: { actionId: 'transition', type: 'toggle', functionName: 'ftb' },
	replay_state: { actionId: 'replay', type: 'toggle', functionName: 'replay' },
	mark_replay: { actionId: 'replay', type: 'toggle', functionName: 'markIn' },
	AUTOSWITCH: { actionId: 'auto_switch', type: 'toggle', functionName: 'autoSwitch' },
	VFA: { actionId: 'auto_switch', type: 'toggle', functionName: 'vfa' },
	audio_fade: { actionId: 'audio', type: 'toggle', functionName: 'audioFade' },
	program_state: { actionId: 'audio', type: 'toggle', functionName: 'programAudio' },
	local_video: { actionId: 'local_video', type: 'toggle' },
	preview_mode: { actionId: 'stream_record', type: 'toggle', functionName: 'programMax' },
	play_status: { actionId: 'bgm', type: 'toggle', functionName: 'playPause' },
	preview_to_program: { actionId: 'director_mode', type: 'toggle', functionName: 'previewToProgram' },
	scoreboard_state: { actionId: 'scoreboard', type: 'toggle', functionName: 'scoreboard' },
	scoretime_state: { actionId: 'scoreboard', type: 'toggle', functionName: 'scoreboardTime' },
	time_state: { actionId: 'scoreboard', type: 'toggle', functionName: 'timeStartPause' },

	// Cycle type
	pgm_toggle: { actionId: 'stream_record', type: 'cycle', functionName: 'pgmOut' },
	pgm_toggle_two: { actionId: 'stream_record', type: 'cycle', functionName: 'pgmOut2' },
	transition_ptp_type: { actionId: 'director_mode', type: 'cycle', functionName: 'directorTransitionMethod' },
	transition_ptp_dir: { actionId: 'director_mode', type: 'cycle', functionName: 'switchMethod' },
	transitions_duration: { actionId: 'transition', type: 'cycle', functionName: 'transitionDuration' },
	transitions_type: { actionId: 'transition', type: 'cycle', functionName: 'transitionMethod' },
	play_mode: { actionId: 'bgm', type: 'cycle', functionName: 'playMode' },

	// Source type
	preview_source_1: { actionId: 'source', type: 'source', functionName: 'source1' },
	preview_source_2: { actionId: 'source', type: 'source', functionName: 'source2' },
	preview_source_3: { actionId: 'source', type: 'source', functionName: 'source3' },
	preview_source_4: { actionId: 'source', type: 'source', functionName: 'source4' },
	preview_source_5: { actionId: 'source', type: 'source', functionName: 'source5' },
	preview_source_6: { actionId: 'source', type: 'source', functionName: 'source6' },
	preview_source_7: { actionId: 'source', type: 'source', functionName: 'source7' },
	preview_source_8: { actionId: 'source', type: 'source', functionName: 'source8' },
	preview_source_9: { actionId: 'source', type: 'source', functionName: 'source9' },
	preview_source_10: { actionId: 'source', type: 'source', functionName: 'source10' },

	// Overlay type
	Overlay_1: { actionId: 'overlay', type: 'overlay', functionName: 'overlay1' },
	Overlay_2: { actionId: 'overlay', type: 'overlay', functionName: 'overlay2' },
	Overlay_3: { actionId: 'overlay', type: 'overlay', functionName: 'overlay3' },
	Overlay_4: { actionId: 'overlay', type: 'overlay', functionName: 'overlay4' },
	Overlay_5: { actionId: 'overlay', type: 'overlay', functionName: 'overlay5' },
	Overlay_6: { actionId: 'overlay', type: 'overlay', functionName: 'overlay6' },
	Overlay_7: { actionId: 'overlay', type: 'overlay', functionName: 'overlay7' },
	Overlay_8: { actionId: 'overlay', type: 'overlay', functionName: 'overlay8' },
	Overlay_9: { actionId: 'overlay', type: 'overlay', functionName: 'overlay9' },
	Overlay_10: { actionId: 'overlay', type: 'overlay', functionName: 'overlay10' },
}
